eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone : http://localhost:8761/eureka
spring:
  config:
    activate:
      on-profile: single
  redis:
    host: localhost
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1