spring:
  config:
    activate:
      on-profile: "redis-docker"
  redis:
    host: redis
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

---
spring:
  config:
    activate:
      on-profile: "redis-local"
  redis:
    host: localhost
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1